/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestion_cafeterias.interfaz_grafica.producto;

import com.gestion_cafeterias.acceso.AccesoProducto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * @author moha
 */
public class MenuActualizar extends javax.swing.JFrame {

    /**
     * Creates new form InsertarMenu
     */
    public MenuActualizar() {
        initComponents();
        jVerify.setVisible(false);
        LabelIdNoExist.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ErrTextArea = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Updatebtn = new javax.swing.JButton();
        jVerify = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LabelIdNoExist = new javax.swing.JLabel();

        Dialog1.setTitle("Exception");
        Dialog1.setSize(new java.awt.Dimension(379, 285));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\DAM1B22\\Pictures\\x-mark-64.png")); // NOI18N
        jLabel5.setText("Error de insercion. Descripcion del Error: ");

        ErrTextArea.setColumns(20);
        ErrTextArea.setRows(5);
        jScrollPane1.setViewportView(ErrTextArea);

        javax.swing.GroupLayout Dialog1Layout = new javax.swing.GroupLayout(Dialog1.getContentPane());
        Dialog1.getContentPane().setLayout(Dialog1Layout);
        Dialog1Layout.setHorizontalGroup(
            Dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        Dialog1Layout.setVerticalGroup(
            Dialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UI Actualizar Producto");
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 89, 100, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 92, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 123, 100, -1));

        jLabel2.setText("Precio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 126, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 157, 100, -1));

        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 191, 102, -1));

        jLabel4.setText("Proveedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 194, -1, -1));

        Updatebtn.setText("Actualizar");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 275, -1, -1));

        jVerify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jVerify.setIcon(new javax.swing.ImageIcon("iconos\\Ok.png"));
        jVerify.setText("Actualizado!");
        getContentPane().add(jVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 242, -1, -1));

        jLabel6.setText("Nota: Actualizar la tabla despues de la insercion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 316, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 37, 100, -1));

        jLabel7.setText("ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 40, -1, -1));

        LabelIdNoExist.setBackground(new java.awt.Color(204, 204, 204));
        LabelIdNoExist.setFont(new java.awt.Font("Sitka Subheading", 3, 12)); // NOI18N
        LabelIdNoExist.setForeground(new java.awt.Color(255, 0, 0));
        LabelIdNoExist.setIcon(new javax.swing.ImageIcon("iconos\\warning2.png"));
        LabelIdNoExist.setMaximumSize(new java.awt.Dimension(0, 0));
        LabelIdNoExist.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(LabelIdNoExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        try {

            boolean actualizado;
            int id = Integer.parseInt(jTextField5.getText());

            String nombre = jTextField1.getText();
            Double precio = Double.valueOf(jTextField2.getText());
            String tipo = jTextField3.getText();
            String proveedor = jTextField4.getText();

            if (AccesoProducto.siExiste(id) == false) {
                LabelIdNoExist.setVisible(true);
                LabelIdNoExist.setText("¡ID no existe!");
            } 
            else {
                actualizado = AccesoProducto.actualizar(id, nombre,
                        precio, tipo, proveedor);
                LabelIdNoExist.setVisible(false);
                if (actualizado) {
                    jVerify.setVisible(true);
                }
            }
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuActualizar.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(MenuActualizar.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (NumberFormatException nfe) {
            LabelIdNoExist.setVisible(true);
            LabelIdNoExist.setText("¡Campo invalido!");
        } 
        catch (Exception e) {
            Dialog1.setVisible(true);
            ErrTextArea.setText(e.getLocalizedMessage());
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_UpdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog1;
    private javax.swing.JTextArea ErrTextArea;
    private javax.swing.JLabel LabelIdNoExist;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jVerify;
    // End of variables declaration//GEN-END:variables
DefaultTableModel modelTabla = new DefaultTableModel();
}
