/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gestion_cafeterias.interfaz_grafica.cafeteria;

import com.gestion_cafeterias.acceso.AccesoCafeteria;
import com.gestion_cafeterias.acceso.AccesoEmpleado;
import com.gestion_cafeterias.modelo.Cafeteria;
import com.gestion_cafeterias.util.Constantes;
import com.gestion_cafeterias.util.PopUpError;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario Fernández
 */
public class InsertarActualizarCafeteria extends javax.swing.JDialog {

    private static final int MODO_INSERTAR = 0;
    private static final int MODO_ACTUALIZAR = 1;
    private static final String GERENTE_SIN_ASIGNAR = "Sin asignar";
    private static final String ERROR_HORARIO = "El horario no puede estar vacío.";
    private static final String ERROR_DIRECCION = "La dirección no puede estar vacía.";
    private static final String ERROR_ALQUILER = "El precio de alquiler debe existir y ser mayor que 0.";
    private static final String ERROR_AFORO = "El aforo debe ser mayor que 0.";
    private int modo = -1;
    private int idCafeteria;

    /**
     * Creates new form InsertarCafeteria
     *
     * @param parent
     * @param modal
     */
    public InsertarActualizarCafeteria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            inicializarComponentes();
            jButtonAccion.setText("Insertar");
            jLabelTitulo.setText("Insertar cafetería");
            modo = MODO_INSERTAR;
        } catch (ClassNotFoundException | SQLException ex) {
            mostrarError(Constantes.ERROR_BBDD);
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            mostrarError(Constantes.ERROR_INESPERADO);
            Logger.getLogger(ConsultarCafeterias.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    public InsertarActualizarCafeteria(java.awt.Frame parent, boolean modal, int idCafeteria) {
        super(parent, modal);
        try {
            inicializarComponentes();
            jButtonAccion.setText("Actualizar");
            jLabelTitulo.setText("Actualizar cafetería");
            Cafeteria cafeteria = AccesoCafeteria.consultar(idCafeteria);
            if (cafeteria != null) {
                this.idCafeteria = cafeteria.getIdCafeteria();
                jTextFieldAlquiler.setText(String.valueOf(cafeteria.getPrecioAlquiler()));
                jTextFieldDireccion.setText(cafeteria.getDireccion());
                jTextFieldHorario.setText(cafeteria.getHorario());
                jSpinnerAforo.setValue(cafeteria.getAforoLocal());
                String nombreGerente = cafeteria.getNombreGerente();
                if (nombreGerente != null) {
                    jComboGerente.setSelectedItem(nombreGerente);
                } else {
                    jComboGerente.setSelectedItem(GERENTE_SIN_ASIGNAR);
                }

                modo = MODO_ACTUALIZAR;

            }
        } catch (ClassNotFoundException | SQLException ex) {
            mostrarError(Constantes.ERROR_BBDD);
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            mostrarError(Constantes.ERROR_INESPERADO);
            Logger.getLogger(ConsultarCafeterias.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void inicializarComponentes() throws ClassNotFoundException, SQLException {
        initComponents();
        List<String> empleados = AccesoEmpleado.consultarNombres();
        empleados.addFirst(GERENTE_SIN_ASIGNAR);
        modeloGerentes = new DefaultComboBoxModel(empleados.toArray());
        jComboGerente.setModel(modeloGerentes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldHorario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerAforo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlquiler = new javax.swing.JTextField();
        jComboGerente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonAccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Insertar cafetería");

        jLabel2.setText("Horario");

        jLabel3.setText("Dirección");

        jLabel4.setText("Aforo local");

        jLabel5.setText("Precio alquiler");

        jComboGerente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Gerente");

        jButtonAccion.setText("Insertar");
        jButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAccion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAforo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDireccion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHorario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboGerente, 0, 246, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAlquiler)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccionActionPerformed
        // TODO add your handling code here:
        List<String> errores = new ArrayList<>();
        String horario = jTextFieldHorario.getText();
        String direccion = jTextFieldDireccion.getText();
        int aforoLocal = (Integer) jSpinnerAforo.getValue();

        if (horario == null || horario.isBlank()) {
            errores.add(ERROR_HORARIO);
        }
        if (direccion == null || direccion.isBlank()) {
            errores.add(ERROR_DIRECCION);
        }
        if (aforoLocal < 1) {
            errores.add(ERROR_AFORO);
        }

        String nombreGerente = (String) jComboGerente.getSelectedItem();
        if (nombreGerente.equals(GERENTE_SIN_ASIGNAR)) {
            nombreGerente = null;
        }

        try {
            if (jTextFieldAlquiler.getText() == null
                    || jTextFieldAlquiler.getText().isEmpty()
                    || Double.parseDouble(jTextFieldAlquiler.getText()) <= 0) {
                errores.add(ERROR_ALQUILER);
            }
            if (errores.isEmpty()) {
                double precioAlquiler = Double.parseDouble(jTextFieldAlquiler.getText());

                if (modo == MODO_INSERTAR) {
                    Cafeteria nuevaCafeteria = new Cafeteria(horario, direccion,
                            aforoLocal, precioAlquiler, nombreGerente);

                    AccesoCafeteria.insertar(nuevaCafeteria);
                } else if (modo == MODO_ACTUALIZAR) {
                    Cafeteria nuevaCafeteria = new Cafeteria(idCafeteria, horario,
                            direccion, aforoLocal, precioAlquiler, nombreGerente);

                    AccesoCafeteria.actualizar(nuevaCafeteria);
                }
                this.dispose();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            errores.add(Constantes.ERROR_BBDD);
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            errores.add(Constantes.ERROR_STRING_NO_NUMERICO);
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            errores.add(Constantes.ERROR_INESPERADO);
            Logger.getLogger(ConsultarCafeterias.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            if (!errores.isEmpty()) {
                mostrarErrores(errores);
            }
        }
    }//GEN-LAST:event_jButtonAccionActionPerformed

    private void mostrarErrores(List<String> errores) {
        PopUpError.mostrarErrores(this, errores);
    }

    private void mostrarError(String error) {
        PopUpError.mostrarError(this, error);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            InsertarActualizarCafeteria dialog = new InsertarActualizarCafeteria(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccion;
    private javax.swing.JComboBox<String> jComboGerente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerAforo;
    private javax.swing.JTextField jTextFieldAlquiler;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldHorario;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel modeloGerentes;
}
