/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.gestioncafeterias.interfazGrafica;

import com.gestioncafeterias.interfazGrafica.cafeteria.ConsultarCafeterias;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author DAM1B11
 */
public class NewMDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewMDIApplication
     */
    public NewMDIApplication() {
        initComponents();
        ventanaCafeterias = new ConsultarCafeterias();

    } 

    private void iniciarFrame(JFrame jFrame) {
        JInternalFrame internalFrame = new JInternalFrame();
        internalFrame.setContentPane(jFrame.getContentPane());
        internalFrame.pack();

        Dimension desktopSize = desktopPane.getSize();
        Dimension jInternalFrameSize = internalFrame.getSize();
        internalFrame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        internalFrame.setVisible(true);
        desktopPane.add(internalFrame);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        cafeteriasMenu = new javax.swing.JMenu();
        abrirCafeteriasMenuItem = new javax.swing.JMenuItem();
        empleadosMenu = new javax.swing.JMenu();
        abrirEmpleadosMenuItem = new javax.swing.JMenuItem();
        productosMenu = new javax.swing.JMenu();
        abrirProductosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        desktopPane.setPreferredSize(new java.awt.Dimension(850, 500));
        desktopPane.setRequestFocusEnabled(false);

        cafeteriasMenu.setMnemonic('f');
        cafeteriasMenu.setText("Cafeterías");

        abrirCafeteriasMenuItem.setMnemonic('o');
        abrirCafeteriasMenuItem.setText("Abrir");
        abrirCafeteriasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCafeteriasMenuItemActionPerformed(evt);
            }
        });
        cafeteriasMenu.add(abrirCafeteriasMenuItem);

        menuBar.add(cafeteriasMenu);

        empleadosMenu.setMnemonic('e');
        empleadosMenu.setText("Empleados");

        abrirEmpleadosMenuItem.setMnemonic('t');
        abrirEmpleadosMenuItem.setText("Abrir");
        empleadosMenu.add(abrirEmpleadosMenuItem);

        menuBar.add(empleadosMenu);

        productosMenu.setMnemonic('h');
        productosMenu.setText("Productos");

        abrirProductosMenuItem.setMnemonic('c');
        abrirProductosMenuItem.setText("Abrir");
        productosMenu.add(abrirProductosMenuItem);

        menuBar.add(productosMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCafeteriasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCafeteriasMenuItemActionPerformed
        iniciarFrame(ventanaCafeterias);
    }//GEN-LAST:event_abrirCafeteriasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirCafeteriasMenuItem;
    private javax.swing.JMenuItem abrirEmpleadosMenuItem;
    private javax.swing.JMenuItem abrirProductosMenuItem;
    private javax.swing.JMenu cafeteriasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productosMenu;
    // End of variables declaration//GEN-END:variables

    private JFrame ventanaCafeterias;
    private JFrame ventanaEmpleados;
    private JFrame ventanaProductos;
}
