/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestion_cafeterias.interfaz_grafica.empleado;

import com.gestion_cafeterias.acceso.AccesoEmpleado;
import com.gestion_cafeterias.modelo.Empleado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM1B07
 */
public class ConsultaEmpleados extends javax.swing.JFrame {

    DefaultTableModel modelTabla = new DefaultTableModel();

    /**
     * Creates new form ConsultaEmpleados
     */
    public ConsultaEmpleados() {
        initComponents();

        modelTabla.addColumn("ID");
        modelTabla.addColumn("Nombre");
        modelTabla.addColumn("Salario €");
        modelTabla.addColumn("Fecha de Alta");
        modelTabla.addColumn("DNI");

        mostrarEmpleados();

    }

    private void mostrarEmpleados() {
        try {
            List<Empleado> listaEmpleados;

            listaEmpleados = AccesoEmpleado.consultarTodos();

            String[] datos = new String[5];

            for (Empleado empleado : listaEmpleados) {

                datos[0] = String.valueOf(empleado.getIdEmpleado());
                datos[1] = empleado.getNombre();
                datos[2] = String.valueOf(empleado.getSalario());
                datos[3] = empleado.getFechaAlta();
                datos[4] = empleado.getDni();
                modelTabla.addRow(datos);

            }
            jTableTodos.setModel(modelTabla);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getSelectedID() {
        int row = jTableTodos.getSelectedRow();
        String value = jTableTodos.getModel().getValueAt(row, 0).toString();
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTodos = new javax.swing.JTable();
        botonInsertar = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        botonRefresh = new javax.swing.JButton();
        lblExito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTodos);

        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonConsultar.setText("Consultar ");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        labelCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCodigo.setText("Codigo:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonRefresh.setText("Actualizar Tabla");
        botonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefreshActionPerformed(evt);
            }
        });

        lblExito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblExito.setForeground(new java.awt.Color(102, 204, 0));
        lblExito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCodigo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonConsultar)
                        .addGap(82, 82, 82)
                        .addComponent(botonActualizar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(botonInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminar)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblExito, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(botonRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRefresh)
                    .addComponent(lblExito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblError)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultar)
                    .addComponent(botonActualizar)
                    .addComponent(botonInsertar)
                    .addComponent(botonEliminar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        try {
            int delay = 1500;
            lblError.setText("");
            String id_empleado = txtCodigo.getText();
            int codigo = Integer.parseInt(id_empleado);
            Empleado empleado = AccesoEmpleado.consultar(codigo);

            if (empleado == null) {
                lblError.setText("No existe ningun empleado con ese codigo");
            } else if (!AccesoEmpleado.esGerenteEliminar(codigo)) {
                
                Timer timer = new Timer(delay, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                     lblExito.setText("");
                    ((Timer) e.getSource()).stop();
                }
            });
            timer.start();
            lblExito.setText("ACCIÓN DE ELIMINAR EXITOSA");
            } else {
                EliminarGerente eliminar = new EliminarGerente(id_empleado);
                eliminar.setVisible(true);
            }

        } catch (NumberFormatException nfe) {
            lblError.setText("Escribe un numero en el cuadro de codigo");
        } catch (ClassNotFoundException cnfe) {
            lblError.setText("Error al conectar con la base de datos");
        } catch (SQLException sqle) {
            lblError.setText("Error con la base de datos");
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        try {
            lblError.setText("");
            int codigo = Integer.parseInt(txtCodigo.getText());
            Empleado empleado = AccesoEmpleado.consultar(codigo);
            String[] datos = new String[5];
            if (empleado == null) {
                lblError.setText("No existe ningun empleado con ese codigo");
            } else {
                modelTabla.setRowCount(0);
                datos[0] = String.valueOf(empleado.getIdEmpleado());
                datos[1] = empleado.getNombre();
                datos[2] = String.valueOf(empleado.getSalario());
                datos[3] = empleado.getFechaAlta();
                datos[4] = empleado.getDni();
                modelTabla.addRow(datos);
            }

        } catch (NumberFormatException nfe) {
            lblError.setText("Escribe un numero en el cuadro de codigo");
        } catch (ClassNotFoundException cnfe) {
            lblError.setText("Error al conectar con la base de datos");
        } catch (SQLException sqle) {
            lblError.setText("Error con la base de datos");
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefreshActionPerformed
        modelTabla.setRowCount(0);
        mostrarEmpleados();
    }//GEN-LAST:event_botonRefreshActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        try {
            String id_empleado = txtCodigo.getText();
            Empleado empleado = AccesoEmpleado.consultar(Integer.parseInt(txtCodigo.getText()));
            if (empleado == null) {
                lblError.setText("No existe ningun empleado con ese codigo");
            } else {
                ActualizarEmpleado actualizar = new ActualizarEmpleado(id_empleado);
                actualizar.setVisible(true);
            }
        } catch (NumberFormatException nfe) {
            lblError.setText("Escribe un numero en el cuadro de codigo para poder actualizar");
        } catch (ClassNotFoundException cnfe) {
            lblError.setText("Error al conectar con la base de datos");
        } catch (SQLException sqle) {
            lblError.setText("Error con la base de datos");
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        InsertarEmpleado insertar = new InsertarEmpleado();
        insertar.setVisible(true);
    }//GEN-LAST:event_botonInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTodos;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblExito;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
