/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gestioncafeterias.interfazGrafica.cafeteria;

import com.gestioncafeterias.acceso.AccesoCafeteria;
import com.gestioncafeterias.acceso.AccesoEmpleado;
import com.gestioncafeterias.modelo.Cafeteria;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mario Fernández
 */
public class InsertarActualizarCafeteria extends javax.swing.JDialog {

    private static final int MODO_INSERTAR = 0;
    private static final int MODO_ACTUALIZAR = 1;
    private int modo = -1;
    private int idCafeteria;

    /**
     * Creates new form InsertarCafeteria
     *
     * @param parent
     * @param modal
     */
    public InsertarActualizarCafeteria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            inicializarComponentes();
            jButtonAccion.setText("Insertar");
            modo = MODO_INSERTAR;
        } catch (ClassNotFoundException | SQLException ex) {
            jLabelError.setText("Error de BBDD");
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public InsertarActualizarCafeteria(java.awt.Frame parent, boolean modal, int idCafeteria) {
        super(parent, modal);
        try {
            inicializarComponentes();
            jButtonAccion.setText("Actualizar");
            Cafeteria cafeteria = AccesoCafeteria.consultar(idCafeteria);
            if (cafeteria != null) {
                this.idCafeteria = cafeteria.getIdCafeteria();
                jTextFieldAlquiler.setText(String.valueOf(cafeteria.getPrecioAlquiler()));
                jTextFieldDireccion.setText(cafeteria.getDireccion());
                jTextFieldHorario.setText(cafeteria.getHorario());
                jSpinnerAforo.setValue(cafeteria.getAforoLocal());
                jComboGerente.setSelectedItem(cafeteria.getNombreGerente());
                modo = MODO_ACTUALIZAR;

            }
        } catch (ClassNotFoundException | SQLException ex) {
            jLabelError.setText("Error de BBDD");
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void inicializarComponentes() throws ClassNotFoundException, SQLException {
        initComponents();
        List<String> empleados = AccesoEmpleado.consultarNombres();
        modeloGerentes = new DefaultComboBoxModel(empleados.toArray());
        jComboGerente.setModel(modeloGerentes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldHorario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerAforo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlquiler = new javax.swing.JTextField();
        jComboGerente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonAccion = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insertar cafetería");

        jTextFieldHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Horario");

        jLabel3.setText("Dirección");

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Aforo local");

        jLabel5.setText("Precio alquiler");

        jTextFieldAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlquilerActionPerformed(evt);
            }
        });

        jComboGerente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Gerente");

        jButtonAccion.setText("Insertar");
        jButtonAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccionActionPerformed(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAforo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDireccion))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHorario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboGerente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAlquiler)))
                            .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addComponent(jButtonAccion)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAccion)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorarioActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlquilerActionPerformed

    private void jButtonAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccionActionPerformed
        // TODO add your handling code here:
        jLabelError.setText("");
        String horario = jTextFieldHorario.getText();
        String direccion = jTextFieldDireccion.getText();
        int aforoLocal = (Integer) jSpinnerAforo.getValue();
        String nombreGerente = (String) jComboGerente.getSelectedItem();

        try {
            if (jTextFieldAlquiler.getText() == null
                    || jTextFieldAlquiler.getText().isEmpty()
                    || Double.parseDouble(jTextFieldAlquiler.getText()) <= 0) {
                jLabelError.setText("El precio de alquiler debe ser mayor que 0.");

            } else {
                double precioAlquiler = Double.parseDouble(jTextFieldAlquiler.getText());

                if (modo == MODO_INSERTAR) {
                    Cafeteria nuevaCafeteria = new Cafeteria(horario, direccion,
                            aforoLocal, precioAlquiler, nombreGerente);

                    AccesoCafeteria.insertar(nuevaCafeteria);
                } else if (modo == MODO_ACTUALIZAR) {
                    Cafeteria nuevaCafeteria = new Cafeteria(idCafeteria, horario,
                            direccion, aforoLocal, precioAlquiler, nombreGerente);

                    AccesoCafeteria.actualizar(nuevaCafeteria);
                }
                this.dispose();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            jLabelError.setText("Error de BBDD");
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            jLabelError.setText("El dato debe ser numérico.");
            Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarActualizarCafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            InsertarActualizarCafeteria dialog = new InsertarActualizarCafeteria(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccion;
    private javax.swing.JComboBox<String> jComboGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JSpinner jSpinnerAforo;
    private javax.swing.JTextField jTextFieldAlquiler;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldHorario;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel modeloGerentes;
}
